Deployment fixes
cockroachdb/backboard pull request #5
Opened 2021-03-16 01:18 UTC by rail

* Add brief README.md
* Fix DB URL to reflect the actual value
* Set the branch to 21.1
* Use `master` tag instead of `master-bob` tag in `k8s/backboard.yaml`.
  In order this to work, I removed the `-$USER` suffix from one of the
  tags. This tag was not used explicitly (the push.sh script uses
  $SHA-$USER).

2021-03-17 01:40 UTC, jlinder reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/backboard/5)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @rail)

___
*[push.sh, line 5 at r1](https://reviewable.io/reviews/cockroachdb/backboard/5#-MVxnh5V60LHL3PuMXZb:-MVxnh5V60LHL3PuMXZc:b-v94zc7) ([raw file](https://github.com/cockroachdb/backboard/blob/d029ad04d4361dc05e88e51daaab8b10e5e1ad1a/push.sh#L5)):*
> ```Shell
> 
> # Upload the working directory to be built.
> BRANCH=$(git symbolic-ref --short HEAD)
> ```

A couple thoughts on Removing `-$USER` from the branch:

- I'm curious why this change?
- This makes it so that the builds in `gcloud --project cockroach-dev-inf builds list` show up as generic `master` and without an indication of who initiated the build (though the SHORT_SHA does show up in the logs for the build as the tag for the docker image)
- What is on the person's local master isn't necessarily actually on the remote master
___
*[README.md, line 18 at r1](https://reviewable.io/reviews/cockroachdb/backboard/5#-MVxk0cqCUcE0jipefww:-MVxk0cr1K59jbk_qPPa:b-hk2npg) ([raw file](https://github.com/cockroachdb/backboard/blob/d029ad04d4361dc05e88e51daaab8b10e5e1ad1a/README.md#L18)):*
> ```
> manitest
> ```

sp: `manifest`


<!-- Sent from Reviewable.io -->

2021-03-17 01:52 UTC, rail reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/backboard/5)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jlinder and @rail)

___
*[push.sh, line 5 at r1](https://reviewable.io/reviews/cockroachdb/backboard/5#-MVxnh5V60LHL3PuMXZb:-MVxqAgHEtsQDGHEVAGU:bs1ruqm) ([raw file](https://github.com/cockroachdb/backboard/blob/d029ad04d4361dc05e88e51daaab8b10e5e1ad1a/push.sh#L5)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

A couple thoughts on Removing `-$USER` from the branch:

- I'm curious why this change?
- This makes it so that the builds in `gcloud --project cockroach-dev-inf builds list` show up as generic `master` and without an indication of who initiated the build (though the SHORT_SHA does show up in the logs for the build as the tag for the docker image)
- What is on the person's local master isn't necessarily actually on the remote master
</blockquote></details>

The rationale behind this was changing the manifest so it uses something not out of date. When I ran `kubectl apply -f ...` it updated the image to something that Bob built way back ago.

Ideally, we should use the same image in the manifest and in `push.sh`, but that's something for the future. Maybe use kustomize instead of the current approach?

You are right, local master doesn't mean it's pushed, but I'd debate we shouldn't apply something that is local-only. Well, ideally we shouldn't even apply anything, just merge and let the CI do the rest (so we don't even use `$USER`), but that is next. :)
___
*[README.md, line 18 at r1](https://reviewable.io/reviews/cockroachdb/backboard/5#-MVxk0cqCUcE0jipefww:-MVxs_Wh-IC2fHlcQONE:b-896fix) ([raw file](https://github.com/cockroachdb/backboard/blob/d029ad04d4361dc05e88e51daaab8b10e5e1ad1a/README.md#L18)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

> ```
> manitest
> ```

sp: `manifest`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-25 15:29 UTC, jlinder requested changes
> Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/backboard/5)* status: all files reviewed, 1 unresolved discussion (waiting on @rail)

___
*[.DS_Store, line 0 at r2](https://reviewable.io/reviews/cockroachdb/backboard/5#-MWdmkbZBcloz6B50QX4:-MWdmkbZBcloz6B50QX5:b-uzbz2e) ([raw file](https://github.com/cockroachdb/backboard/blob/a575dcbabdceb1c3dab76a167c75dfc05871af5d/.DS_Store#L0)):*
This file doesn't need to be in the source tree. Can you remove it and add `.DS_Store` to the `.gitignore`?
___
*[push.sh, line 5 at r1](https://reviewable.io/reviews/cockroachdb/backboard/5#-MVxnh5V60LHL3PuMXZb:-MW_czsVC0xVtyJ2wJ5C:b-8ms05b) ([raw file](https://github.com/cockroachdb/backboard/blob/d029ad04d4361dc05e88e51daaab8b10e5e1ad1a/push.sh#L5)):*
> Maybe use kustomize instead of the current approach?

Using kustomize seems worth trying. It looks like it's integrated directly into `kubectl`.

> ... I'd debate we shouldn't apply something that is local-only. Well, ideally we shouldn't even apply anything, just merge and let the CI do the rest (so we don't even use $USER), but that is next. :)

Poor wording on my part. I was specifically commenting on the current process. I agree we should not be applying things that are local-only. Having a proper PR + auto-deploy-from-master process is desirable.


<!-- Sent from Reviewable.io -->

2021-03-25 15:57 UTC, rail reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/backboard/5)* status: all files reviewed, 1 unresolved discussion (waiting on @jlinder)

___
*[.DS_Store, line  at r2](https://reviewable.io/reviews/cockroachdb/backboard/5#-MWdmkbZBcloz6B50QX4:-MWe48h-CZ2vSdhw51s5:b-ebapd1) ([raw file](https://github.com/cockroachdb/backboard/blob/a575dcbabdceb1c3dab76a167c75dfc05871af5d/.DS_Store#L)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

This file doesn't need to be in the source tree. Can you remove it and add `.DS_Store` to the `.gitignore`?
</blockquote></details>

Blech! Will remove it.
___
*[push.sh, line 5 at r1](https://reviewable.io/reviews/cockroachdb/backboard/5#-MVxnh5V60LHL3PuMXZb:-MWe4iwH5Hl06Khzw7eA:b-en6wxt) ([raw file](https://github.com/cockroachdb/backboard/blob/d029ad04d4361dc05e88e51daaab8b10e5e1ad1a/push.sh#L5)):*
<details><summary><i>Previously, jlinder (James H. Linder) wrote…</i></summary><blockquote>

> Maybe use kustomize instead of the current approach?

Using kustomize seems worth trying. It looks like it's integrated directly into `kubectl`.

> ... I'd debate we shouldn't apply something that is local-only. Well, ideally we shouldn't even apply anything, just merge and let the CI do the rest (so we don't even use $USER), but that is next. :)

Poor wording on my part. I was specifically commenting on the current process. I agree we should not be applying things that are local-only. Having a proper PR + auto-deploy-from-master process is desirable.
</blockquote></details>

Want me to take a look at kustomize as a part of this PR or a separate one? I can also configure GitHub Actions to build and push docker images that we can use to deploy things.


<!-- Sent from Reviewable.io -->

2021-03-25 17:04 UTC, rail reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/backboard/5)* status: all files reviewed, 1 unresolved discussion (waiting on @jlinder)

___
*[.DS_Store, line  at r2](https://reviewable.io/reviews/cockroachdb/backboard/5#-MWdmkbZBcloz6B50QX4:-MWeKqoI4s5xoxfw6JM-:b-896fix) ([raw file](https://github.com/cockroachdb/backboard/blob/a575dcbabdceb1c3dab76a167c75dfc05871af5d/.DS_Store#L)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Blech! Will remove it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-25 21:00 UTC, jlinder approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/backboard/5#-:-MWfA2IG3LLgFsHAVjwL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rail)

___
*[push.sh, line 5 at r1](https://reviewable.io/reviews/cockroachdb/backboard/5#-MVxnh5V60LHL3PuMXZb:-MWfAEd581rvadLIvCc9:b9scuqw) ([raw file](https://github.com/cockroachdb/backboard/blob/d029ad04d4361dc05e88e51daaab8b10e5e1ad1a/push.sh#L5)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Want me to take a look at kustomize as a part of this PR or a separate one? I can also configure GitHub Actions to build and push docker images that we can use to deploy things.
</blockquote></details>

I think separate PRs specifically for kustomize and pushing/deploying via GitHub actions is fine. They aren't urgent by any means.


<!-- Sent from Reviewable.io -->

2021-03-25 21:14 UTC, merged