Allow filtering by PR label
cockroachdb/backboard pull request #6
Opened 2021-04-15 21:53 UTC by rafiss

This is useful since we have a convention of labelling PRs with things
like `backport-21.1.x`, but we don't have any tooling that actually ties
these labels back to whether or not the PR was backported.

2021-04-15 21:53 UTC, rafiss commented
I haven't tested this!! Would appreciate any tips on how to run backboard locally.

2021-04-17 05:42 UTC, rail requested changes
I have some comments and questions.

I'll prep a change for README.md with instructions how to run this locally, so you can iterate faster.

2021-04-17 05:42 UTC, rail commented on state.go
> +
This method is unused, mind removing it?

```suggestion
```

2021-04-17 05:42 UTC, rail commented on state.go
> +		if labelCount != len(pr.Labels) {
What happens if we remove a label from a PR? Maybe do something similar to what we do for [pr_commits](https://github.com/cockroachdb/backboard/blob/1ddb8749804f2d87f6562b164f459224c0e407d8/state.go#L477)?

2021-04-17 05:42 UTC, rail commented on state.go
> +			if l.GetName() == "" {
I wonder if we should limit the amount of labels we add. The dropdown may become very busy :)
Maybe add filter out all labels that don't meet a fixed list of patterns aka allow list?

2021-04-17 05:42 UTC, rail commented on state.go
> +	// Support for PR labels was added later, so some PRs that are otherwise
How does it behave when we merge this? Not sure if we can backfill labels for older PRs.

2021-04-19 16:18 UTC, rafiss commented on state.go
> +
the `Number()`, `MergedAt()`, and `URL()` functions are unused too -- do you think I should remove those too? I made `Labels()` to follow the convention of making accessors for internal fields.

2021-04-19 16:18 UTC, rafiss commented on state.go
> +)
fixed, thanks!

2021-04-19 16:18 UTC, rafiss commented on state.go
> +		if labelCount != len(pr.Labels) {
This if block is just meant to backfill things initially. This check doesn't replace the one below -- if a label is removed, the code below will still run, and we will see that the updatedAt times don't match, so the PR is not up to date.

2021-04-19 16:18 UTC, rafiss commented on state.go
> +	// Support for PR labels was added later, so some PRs that are otherwise
The logic here is meant to backfill labels for older PRs. If we retrieve a PR from the github API and it has labels, then we do this extra check to see if we have stored any labels for the PR already. If we have not stored labels, then we will update the PRs. If we have stored labels, then we will still do the check below based on updatedAt

2021-04-19 16:43 UTC, rail commented on state.go
> +
I'd say kill'em all! :) Less code less headache. We can add them back anytime when we want them to use, they are very simple getters.

2021-04-19 21:27 UTC, rafiss commented on state.go
> +			if l.GetName() == "" {
That sounds good! The only labels we care about here start with `backport`, so I can add a filter for that.

2021-04-19 21:28 UTC, rafiss commented on state.go
> +
Actually, those ones are used in the templating logic, my bad. I also updated the HTML template to display these Labels too, so it's clear that the filtering actually works.

2021-04-19 21:29 UTC, rail commented on state.go
> +
Ohhh, right. Completely forgot about the template!

2021-04-19 21:31 UTC, rail commented on state.go
> +	// Support for PR labels was added later, so some PRs that are otherwise
It sounds sane to me. We should probably test how it behaves, when you deploy this change against the old db.

2021-04-19 21:37 UTC, rafiss commented
I have made all the changes and it looked good to me locally. Ready for another look whenever you have the time

2021-04-20 14:14 UTC, rail approved these changes

2021-04-20 14:14 UTC, rail commented on state.go
> +	// Support for PR labels was added later, so some PRs that are otherwise
I ran it locally and everything looked good to me.

2021-04-20 14:16 UTC, rail approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/backboard/6)* status: all files reviewed, 1 unresolved discussion (waiting on @rail)

___
*[state.go, line 63 at r1](https://reviewable.io/reviews/cockroachdb/backboard/6#-MYMWc24k_e5tM6o3Rbt-r1-63:-MYgYh7JA7_AnOwso7kI:b4c9lyr) ([raw file](https://github.com/cockroachdb/backboard/blob/63eb652dd83d8d08e6a56b705fa16fc83bb18534/state.go#L63)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

fixed, thanks!
</blockquote></details>

:thumbsup: 


<!-- Sent from Reviewable.io -->

2021-04-20 15:05 UTC, rafiss commented
Thanks for your help! Let me know what you think the next step should be to merge/deploy this. I see there's a `push.sh` so I can give that a shot, or I'm also happy to leave it to you.

2021-04-20 15:43 UTC, rail commented
> Thanks for your help! Let me know what you think the next step should be to merge/deploy this. I see there's a `push.sh` so I can give that a shot, or I'm also happy to leave it to you.

Let me deploy it - want to verify the latest changes we applied to the process.

2021-04-20 15:44 UTC, merged

2021-04-21 22:19 UTC, rail commented
I had to run `GRANT ALL on TABLE pr_labels TO backboard;` as `rail` user, because the `backboard` user had no `DELETE` privileges and what caused `2021-04-21T15:04:21.719560567Z2021/04/21 15:04:21 sync error: pq: user backboard does not have DELETE privilege on relation pr_labels`