Show release tags from all branches
cockroachdb/backboard pull request #9
Opened 2021-06-09 16:08 UTC by rafiss

This makes it easier to see all the releases that have a particular
backport commit.

2021-06-09 16:41 UTC, rail requested changes
Wooooooooo! This is amazing!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/backboard/9#-:-MblcibcBajYYj_0vQYv:b-sqtx2k)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jordanlewis and @rafiss)

___
*[server.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/backboard/9#-MblcrG989bBSXS6d5rF:-MblcrG989bBSXS6d5rG:be82s4y) ([raw file](https://github.com/cockroachdb/backboard/blob/a501aa0976654aa99820b4d53b366f0e5b7c3f8d/server.go#L478)):*
> ```Go
> 			if cIdx, backported := re.branchCommits[releaseBranch].messageIDs[c.MessageID()]; backported {
> 				backportCommit := re.branchCommits[releaseBranch].commits[cIdx]
> 				oldestTags = append(oldestTags, backportCommit.oldestTag)
> ```

Hmm, this is how it looks now.
![image.png](https://files.reviewableusercontent.io/images/reviewable/42865/FUZTnRr4Y1HFIyr1chzDvTyj/image.png)

I wonder where these empty space tags come from....


<!-- Sent from Reviewable.io -->

2021-06-09 19:13 UTC, rafiss reviewed
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/backboard/9)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jordanlewis and @rail)

___
*[server.go, line 478 at r1](https://reviewable.io/reviews/cockroachdb/backboard/9#-MblcrG989bBSXS6d5rF:-MbmBEhzDolvXGnUPldE:b-ypfc3h) ([raw file](https://github.com/cockroachdb/backboard/blob/a501aa0976654aa99820b4d53b366f0e5b7c3f8d/server.go#L478)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Hmm, this is how it looks now.
![image.png](https://files.reviewableusercontent.io/images/reviewable/42865/FUZTnRr4Y1HFIyr1chzDvTyj/image.png)

I wonder where these empty space tags come from....
</blockquote></details>

ah i see, it happens if a commit has been backported, but not released yet.


<!-- Sent from Reviewable.io -->

2021-06-09 21:08 UTC, rail commented
LGTM, let me just verify how it looks now. It may take some time

2021-06-10 10:59 UTC, rail approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/backboard/9#-:-MbmOTIc31y6ndOWv10B:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jordanlewis)



<!-- Sent from Reviewable.io -->

2021-06-10 10:59 UTC, merged

2021-06-10 11:38 UTC, rail commented
![image](https://user-images.githubusercontent.com/42865/121518762-d9cd1f00-c9be-11eb-84e0-05ecc7a081de.png)
❤️